# Site
title:              externIE
bio:                '你想把名字留在别人的人事簿上<br/>还是跟我一起把名字留在互联网的历史里'
description:        "externIE的个人博客"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
#locale:             en_US
url:                

#页面资源字符串
str_home:           首页
str_about:          关于
str_posts:          博文
str_tags:           类别
str_projects:       项目

str_weibo:          微博

str_back:           返回
str_learnMore:      了解更多
str_readMore:       更多
str_menuOpen:       菜单

str_allPosts:       所有博文
str_allProjects:    所有项目
str_allTags:        所有类别


# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   externie

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              externie@outlook.com
# twitter:            username
# facebook:           username
github:             externIE
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
# instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             ielinyikai
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
